spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: loan-service
              uri: lb://loan-service
              predicates:
                - Path=/loans/**
            - id: credit-score-service
              uri: lb://credit-score-service  
              predicates:
                - Path=/scores/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

server:
  port: 8080

main:
  web-application-type: reactive

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://localhost:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"
  level:
    root: INFO
    com.gs: DEBUG
  file:
    name: logs/api-gateway.log