name: Java CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Docker Build
      run: |
        docker build -t auth-service ./auth-service
        docker build -t user-service ./user-service
        docker build -t loan-service ./loan-service
        docker build -t api-gateway ./api-gateway
        docker build -t discovery-server ./discovery-server

    # Optional: Push to Docker Hub
    # - name: Login to DockerHub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Docker Push
    #   run: docker push yourusername/auth-service

    - name: Docker Compose Up
      run: docker-compose up -d
